---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/cf-resource
    tag: latest

inputs:
- name: resource-git

run:
  path: sh
  args:
  - -exc
  - |
    cd resource-git \
    && cf api ${api} --skip-ssl-validation \
    && cf login -u ${username} -p ${password} -o ${organization} -s ${space} \
    && cf rename ${current_app_name} ${current_app_name}-existing \
    && cf push ${current_app_name} -f ${manifest} --no-start \
    && cf start ${current_app_name} \
    && cf map-route ${current_app_name} --hostname ${host} \
    && cf delete -f ${current_app_name}-existing
